version: 2
formats: all

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

    - requirements: dev-requirements.txt
    - requirements: doc-requirements.txt
